/var/spool/slurm/slurmd/job10440280/slurm_script: line 31: ./images: Is a directory
Traceback (most recent call last):
  File "/home/lcur0649/uvadlc_practicals_2022/assignment2/part2/cross_dataset.py", line 25, in <module>
    from utils import DummyArgs
ImportError: cannot import name 'DummyArgs' from 'utils' (/home/lcur0649/uvadlc_practicals_2022/assignment2/part2/utils.py)
